const deck = [
	{ value: 6, color: 'a' },
	{ value: 7, color: 'a' },
	{ value: 8, color: 'a' },
	{ value: 9, color: 'a' },
	{ value: 10, color: 'a' },
	{ value: 11, color: 'a' },
	{ value: 12, color: 'a' },
	{ value: 13, color: 'a' },
	{ value: 14, color: 'a' },
	{ value: 6, color: 'b' },
	{ value: 7, color: 'b' },
	{ value: 8, color: 'b' },
	{ value: 9, color: 'b' },
	{ value: 10, color: 'b' },
	{ value: 11, color: 'b' },
	{ value: 12, color: 'b' },
	{ value: 13, color: 'b' },
	{ value: 14, color: 'b' },
	{ value: 6, color: 'c' },
	{ value: 7, color: 'c' },
	{ value: 8, color: 'c' },
	{ value: 9, color: 'c' },
	{ value: 10, color: 'c' },
	{ value: 11, color: 'c' },
	{ value: 12, color: 'c' },
	{ value: 13, color: 'c' },
	{ value: 14, color: 'c' },
	{ value: 6, color: 'd' },
	{ value: 7, color: 'd' },
	{ value: 8, color: 'd' },
	{ value: 9, color: 'd' },
	{ value: 10, color: 'd' },
	{ value: 11, color: 'd' },
	{ value: 12, color: 'd' },
	{ value: 13, color: 'd' },
	{ value: 14, color: 'd' },
];

module.exports = deck;
